const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

const checks = [
  {
    id: 'mobile-requirements-doc',
    file: 'docs/MOBILE_REQUIREMENTS.md',
    contains: ['# 移动端需求文档', 'API 30', '移动端交互适配', '待确认的重要技术选型']
  },
  {
    id: 'agent-rules',
    file: 'AGENT.md',
    contains: ['与用户对话时使用中文', '优先使用 ctx_* 工具', 'Java', 'API 30']
  },
  {
    id: 'android-gradle-files',
    file: 'app/build.gradle',
    contains: ["compileSdk 30", "targetSdk 30", "namespace 'com.example.calmobile'"]
  },
  {
    id: 'android-manifest-main-activity',
    file: 'app/src/main/AndroidManifest.xml',
    contains: ['MainActivity', 'android.intent.action.MAIN', 'android.intent.category.LAUNCHER']
  },
  {
    id: 'java-entry-activity',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['package com.example.calmobile;', 'extends Activity', 'setContentView(R.layout.activity_main)']
  },
  {
    id: 'fake-data-flow-java',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['class Exhibition', 'SAMPLE_EXHIBITIONS', 'buildMonthGrid', 'showExhibitionDetail', 'showRegistrationForm', 'submitRegistration']
  },
  {
    id: 'fake-data-flow-layout',
    file: 'app/src/main/res/layout/activity_main.xml',
    contains: ['@+id/calendar_grid', '@+id/exhibition_list', '@+id/detail_panel', '@+id/registration_panel', '@+id/registration_answers', '@+id/my_registrations_title', '@+id/my_registrations_list']
  },
  {
    id: 'fake-data-flow-strings',
    file: 'app/src/main/res/values/strings.xml',
    contains: ['报名信息', '提交报名', '今日展会', '展会详情', '我的报名', '取消报名', '暂无报名记录']
  },
  {
    id: 'my-registrations-java-wiring',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['RegistrationManager', 'renderMyRegistrations', 'registrationManager.submit', 'registrationManager.cancel', 'myRegistrationsList']
  },
  {
    id: 'gradle-wrapper-properties',
    file: 'gradle/wrapper/gradle-wrapper.properties',
    contains: ['distributionUrl=https\\://services.gradle.org/distributions/gradle-7.6.4-bin.zip']
  },
  {
    id: 'gradle-wrapper-batch-script',
    file: 'gradlew.bat',
    contains: ['Gradle startup script for Windows', 'gradle\\wrapper\\gradle-wrapper.jar']
  },
  {
    id: 'gradle-wrapper-shell-script',
    file: 'gradlew',
    contains: ['Gradle start up script for POSIX generated by Gradle', 'gradle/wrapper/gradle-wrapper.jar']
  },
  {
    id: 'gradle-wrapper-jar',
    file: 'gradle/wrapper/gradle-wrapper.jar',
    minBytes: 30000
  },
  {
    id: 'original-todo-preserved',
    file: 'TODO.md',
    contains: ['帮我做一个排期规划应用', '网站首页', '管理员页面']
  },
  {
    id: 'profile-activity-java',
    file: 'app/src/main/java/com/example/calmobile/ProfileActivity.java',
    contains: ['package com.example.calmobile;', 'extends Activity', 'ProfileActivity', 'nickname', 'bio', 'contact']
  },
  {
    id: 'profile-activity-layout',
    file: 'app/src/main/res/layout/activity_profile.xml',
    contains: ['@+id/profile_header', '@+id/profile_info', '@+id/profile_edit_fields']
  },
  {
    id: 'profile-manifest-registered',
    file: 'app/src/main/AndroidManifest.xml',
    contains: ['ProfileActivity']
  },
  {
    id: 'profile-strings',
    file: 'app/src/main/res/values/strings.xml',
    contains: ['个人主页', '昵称', '简介', '联系方式']
  },
  {
    id: 'profile-navigation',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['ProfileActivity', 'go_to_profile']
  },
  {
    id: 'user-public-activity-java',
    file: 'app/src/main/java/com/example/calmobile/UserPublicActivity.java',
    contains: ['package com.example.calmobile;', 'extends Activity', 'UserPublicActivity', 'nickname', 'bio', 'contact']
  },
  {
    id: 'user-public-activity-layout',
    file: 'app/src/main/res/layout/activity_user_public.xml',
    contains: ['@+id/user_public_header', '@+id/user_public_info', '@+id/user_public_registrations']
  },
  {
    id: 'user-public-manifest-registered',
    file: 'app/src/main/AndroidManifest.xml',
    contains: ['UserPublicActivity']
  },
  {
    id: 'user-public-strings',
    file: 'app/src/main/res/values/strings.xml',
    contains: ['user_public_title', 'user_public_view_profile_hint']
  },
  {
    id: 'user-public-navigation',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['UserPublicActivity', 'openUserPublicProfile']
  },
  {
    id: 'exhibitor-backend-activity-java',
    file: 'app/src/main/java/com/example/calmobile/ExhibitorBackendActivity.java',
    contains: ['package com.example.calmobile;', 'extends Activity', 'ExhibitorBackendActivity', 'ExhibitionManager', 'saveExhibition']
  },
  {
    id: 'exhibitor-backend-navigation-layout',
    file: 'app/src/main/res/layout/activity_main.xml',
    contains: ['@+id/go_to_exhibitor_backend_btn']
  },
  {
    id: 'exhibitor-backend-manifest',
    file: 'app/src/main/AndroidManifest.xml',
    contains: ['ExhibitorBackendActivity']
  },
  {
    id: 'exhibitor-backend-strings',
    file: 'app/src/main/res/values/strings.xml',
    contains: ['exhibitor_backend_title', 'exhibitor_add_exhibition']
  },
  {
    id: 'exhibitor-backend-navigation',
    file: 'app/src/main/java/com/example/calmobile/MainActivity.java',
    contains: ['ExhibitorBackendActivity', 'exhibitorBackendButton']
  },
  {
    id: 'registration-management-activity-java',
    file: 'app/src/main/java/com/example/calmobile/RegistrationManagementActivity.java',
    contains: ['package com.example.calmobile;', 'extends Activity', 'RegistrationManagementActivity', 'MgmtRecord']
  },
  {
    id: 'registration-management-manifest',
    file: 'app/src/main/AndroidManifest.xml',
    contains: ['RegistrationManagementActivity']
  },
  {
    id: 'registration-management-strings',
    file: 'app/src/main/res/values/strings.xml',
    contains: ['reg_mgmt_approve', 'reg_mgmt_reject']
  }
];

let failed = false;
for (const check of checks) {
  const fullPath = path.join(root, check.file);
  if (!fs.existsSync(fullPath)) {
    console.error(`FAIL ${check.id}: missing ${check.file}`);
    failed = true;
    continue;
  }
  const stat = fs.statSync(fullPath);
  if (check.minBytes && stat.size < check.minBytes) {
    console.error(`FAIL ${check.id}: ${check.file} is ${stat.size} bytes, expected at least ${check.minBytes}`);
    failed = true;
  }
  if (!check.contains) {
    continue;
  }
  const content = fs.readFileSync(fullPath, 'utf8');
  for (const expected of check.contains) {
    if (!content.includes(expected)) {
      console.error(`FAIL ${check.id}: ${check.file} does not contain ${expected}`);
      failed = true;
    }
  }
}

if (failed) {
  process.exit(1);
}

console.log(`PASS smoke-check: ${checks.length} project scaffold checks passed`);


